SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = rule30
SOURCEDIR     = .
BUILDDIR      = _build

html:

# $(O) is meant as a shortcut for $(SPHINXOPTS).
%:
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
